language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then sudo add-apt-repository -y ppa:moti-p/cc; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then sudo apt-get -y --reinstall install imagemagick; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install imagick-beta; fi

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-text --coverage-clover coverage.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
